### ISSUE TITLE
Configuration could not be saved

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/data-hub#110]
After updating to most recent commit, I'm trying to save the configuration.

Error details:
```
An exception occurred while executing 'DELETE FROM plugin_datahub_workspaces_document WHERE configuration = ?' with params ["products"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pimcore.plugin_datahub_workspaces_document' doesn't exist
```

According to `pimcore:migrations:migrate` there are "No migrations to execute"

**Comment by weisswurstkanone** [comment]
Can you confirm that the mirgation script got executed ?

**Comment by NiklasBr** [comment]
So far I have discovered that the DB tables `plugin_datahub_workspaces_document` does not exist (as the error says) but the tables `plugin_datahub_workspaces_asset` and `plugin_datahub_workspaces_object` does and I cannot get *Version20190904131554* to activate.

**Comment by weisswurstkanone** [comment]
do you see any further details ?

**Comment by NiklasBr** [comment]
Nothing more than that. Also tried this command `pimcore:migrations:execute 20190904131554` but it failed:

```sh
In MigrationException.php line 34:
                                                   
  Could not find migration version 20190904131554
```

**Comment by dvesh3** [comment]
@NiklasBr can you please try with `bin/console pimcore:migrations:execute -v 20190904131554 --bundle=PimcoreDataHubBundle`?

**Comment by NiklasBr** [comment]
That worked @dvesh3 

```sh
WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y

  ++ migrating 20190904131554

     ->         
                    CREATE TABLE IF NOT EXISTS `plugin_datahub_workspaces_document` (
                        `cid` INT(11) UNSIGNED NOT NULL DEFAULT '0',
                        `cpath` VARCHAR(765) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
                        `configuration` VARCHAR(50) NOT NULL DEFAULT '0',
                        `create` TINYINT(1) UNSIGNED NULL DEFAULT '0',
                        `read` TINYINT(1) UNSIGNED NULL DEFAULT '0',
                        `update` TINYINT(1) UNSIGNED NULL DEFAULT '0',
                        `delete` TINYINT(1) UNSIGNED NULL DEFAULT '0',                    
                        PRIMARY KEY (`cid`, `configuration`)                
                        )
                    COLLATE='utf8mb4_general_ci'
                    ENGINE=InnoDB
                    ;            
        

  ++ migrated (3.1s)
```

**Comment by NiklasBr** [comment]
Also, thanks! Question is, why did PimcoreDataHubBundle not execute when other migrations did when running the composer update?

**Comment by NiklasBr** [comment]
This is probably just exposing my lack of knowledge, but shouldn't this DataHub bundle have it's own version of these to run its migrations?

https://github.com/pimcore/pimcore/blob/32fab59e51159de1c8e86af8b0812bcbb00e8217/bundles/CoreBundle/Resources/config/pimcore/default.yml#L239-L255

**Comment by dvesh3** [comment]
Not really.....we can just `MigrationInstaller` class and then it should migrate on every update. please have a look here for docs https://pimcore.com/docs/5.x/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Pimcore_Bundles/Installers.html#page_Migrations

changes https://github.com/pimcore/data-hub/commit/85380ff63c058f7818138f9625891d97c38d198e

**Comment by NiklasBr** [comment]
@dvesh3 I rolled back to previous version then upgraded Data-hub



```
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating pimcore/data-hub dev-master (2e69c9c => 85380ff):  Checking out 85380ff63c
Writing lock file
Generating optimized autoload files
Endroid Installer detected project type "all"
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Pimcore\Composer::postUpdate
> Pimcore\Composer::clearCache

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    

> Pimcore\Composer::installAssets

 Trying to install assets as relative symbolic links.

 --- ------------------------ ------------------ 
      Bundle                   Method / Error    
 --- ------------------------ ------------------ 
  ✔   PimcoreCoreBundle        relative symlink  
  ✔   PimcoreAdminBundle       relative symlink  
  ✔   PimcoreDataHubBundle     relative symlink  
  ✔   AtelesDataImportBundle   relative symlink  
  ✔   AppBundle                relative symlink  
 --- ------------------------ ------------------ 

 [OK] All assets were successfully installed.                                   

> Pimcore\Composer::executeMigrationsUp

 [OK] Pimcore data cache cleared successfully                                   

                    Pimcore Core Migrations                    

Migrating up to 20190807121356 from 20190701141857

  ++ migrating 20190708175236

     -> DELETE FROM documents_translations WHERE language = ''

  ++ migrated (0.14s)

  ++ migrating 20190729085052

     -> ALTER TABLE users_permission_definitions ADD category varchar(50) NOT NULL

  ++ migrated (0.13s)

  ++ migrating 20190802090149

     -> ALTER TABLE documents_newsletter ADD COLUMN plaintext LONGTEXT NULL DEFAULT NULL AFTER sendingMode;

  ++ migrated (0.09s)

  ++ migrating 20190806160450


  ++ migrated (1.17s)

  ++ migrating 20190807121356


  ++ migrated (0.21s)

  ------------------------

  ++ finished in 1.74s
  ++ 5 migrations executed
  ++ 3 sql queries
```

And when loading Pimcore again I get the following exception:

```
Too few arguments to function Pimcore\Extension\Bundle\Installer\MigrationInstaller::__construct(), 0 passed in /var/www/pimcore/vendor/pimcore/data-hub/src/PimcoreDataHubBundle.php on line 146 and exactly 3 expected
```

**Comment by dvesh3** [comment]
can you please check again? looks like your'e not latest commit 2e5daed5902493857fbdde72f137f14176c5d294

**Comment by NiklasBr** [comment]
No migrations ran when composer updating to 2e5daed either

**Comment by dvesh3** [comment]
It should work now! 296190381331c2f2de5cc1ef85baa32b9b5f03f3

**Comment by NiklasBr** [comment]
Nope :( 

It never enters into `Installer::migrateInstall()` or `Version20190904131554::up()`, neither on composer update, nor on loading Pimcore admin. DB table still missing.

```
  - Updating pimcore/data-hub dev-master (2e5daed => 2961903):  Checking out 2961903813
Writing lock file
Generating optimized autoload files
Endroid Installer detected project type "all"
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Pimcore\Composer::postUpdate
> Pimcore\Composer::clearCache

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    

> Pimcore\Composer::installAssets

 Trying to install assets as relative symbolic links.

 --- ------------------------ ------------------ 
      Bundle                   Method / Error    
 --- ------------------------ ------------------ 
  ✔   PimcoreCoreBundle        relative symlink  
  ✔   PimcoreAdminBundle       relative symlink  
  ✔   PimcoreDataHubBundle     relative symlink  
  ✔   AtelesDataImportBundle   relative symlink  
  ✔   AppBundle                relative symlink  
 --- ------------------------ ------------------ 

 [OK] All assets were successfully installed.                                   

> Pimcore\Composer::executeMigrationsUp

 [OK] Pimcore data cache cleared successfully                                   

                    Pimcore Core Migrations                    

No migrations to execute.
```

**Comment by NiklasBr** [comment]
Tried upgrading Pimcore from 6.1.2 to 6.2.0 but that didn't work either.

**Comment by dvesh3** [comment]
maybe you already have latest version in the db 
![screenshot-newtab-2019 09 13-15-46-15](https://user-images.githubusercontent.com/5137917/64867622-0ca58000-d63e-11e9-9eb9-6a1b5d7c5014.png)

**Comment by NiklasBr** [comment]
An update here.

It appears that migration `Version20190614135736` never runs either, the database tables `plugin_datahub_workspaces_asset` and `plugin_datahub_workspaces_object` both still have their `write` columns.

I verified by adding breakpoints in those files.

**Comment by NiklasBr** [comment]
@dvesh3 I saw you committed yesterday just when I wrote the above comment, I tried again:

```sh
composer u pimcore/data-hub
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating pimcore/data-hub dev-master (2e69c9c => 9236939):  Checking out 9236939e0a
Writing lock file
Generating optimized autoload files
Endroid Installer detected project type "all"
ocramius/package-versions:  Generating version class...
> Pimcore\Composer::postUpdate
ocramius/package-versions: ...done generating version class
> Pimcore\Composer::clearCache

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    

> Pimcore\Composer::installAssets

 Trying to install assets as relative symbolic links.

 --- ------------------------ ------------------ 
      Bundle                   Method / Error    
 --- ------------------------ ------------------ 
  ✔   PimcoreCoreBundle        relative symlink  
  ✔   PimcoreAdminBundle       relative symlink  
  ✔   PimcoreDataHubBundle     relative symlink  
  ✔   AtelesDataImportBundle   relative symlink  
  ✔   AppBundle                relative symlink  
 --- ------------------------ ------------------ 

 [OK] All assets were successfully installed.                                   

> Pimcore\Composer::executeMigrationsUp
Skipping migrations ... (either Pimcore is not installed yet or current status of migrations is not available)
> Pimcore\Composer::clearCache

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        

 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    

> Pimcore\Composer::installAssets

 Trying to install assets as relative symbolic links.

 --- ------------------------ ------------------ 
      Bundle                   Method / Error    
 --- ------------------------ ------------------ 
  ✔   PimcoreCoreBundle        relative symlink  
  ✔   PimcoreAdminBundle       relative symlink  
  ✔   PimcoreDataHubBundle     relative symlink  
  ✔   AtelesDataImportBundle   relative symlink  
  ✔   AppBundle                relative symlink  
 --- ------------------------ ------------------ 

 [OK] All assets were successfully installed.                                   
```

**Comment by julmot** [comment]
Also having that issue when creating a new GraphQl endpoint with a fresh install from master:

![000260](https://user-images.githubusercontent.com/8310677/65976805-06523900-e471-11e9-9d02-e46951e76b84.png)
![000261](https://user-images.githubusercontent.com/8310677/65976806-06523900-e471-11e9-8b4f-f3de74ecbc7d.png)

It still saves my configuration into `pimcore/var/config/datahub-configurations.php`, but GraphiQL doesn't show any available schemas:

![000262](https://user-images.githubusercontent.com/8310677/65977118-a0b27c80-e471-11e9-851d-3b7459e636e9.png)


Pimcore: v6.2.1

**Comment by weisswurstkanone** [comment]
is this still relevant?

**Comment by NiklasBr** [comment]
Yes, I never managed to get the automatic migrations running other than doing it manually as above.

**Comment by weisswurstkanone** [comment]
Question: Is this perhaps a Pimcore (core) issue? When running pimcore:migrations:migrate --bundle=PimcoreDataHubBundle it works, but not when part of the regular migrations hooked by the composer scripts.

see https://github.com/pimcore/pimcore/issues/5445

**Comment by NiklasBr** [comment]
I don't know where exactly the root issue exists, unfortunately.

**Comment by weisswurstkanone** [comment]
Still not able to reproduce

**Comment by NiklasBr** [comment]
Tried it in a new environment today, it is still (not) happening. I still have to run the command manually.

Please re-open.

**Comment by weisswurstkanone** [comment]
die you read https://github.com/pimcore/pimcore/issues/5445 ?

**Comment by NiklasBr** [comment]
Yes, the bug hasn't been fixed, and even if it might ultimately be better to fix it upstream it is wrong to close the issue when the issue has not been resolved in any way.
